quizko/Quizko/Core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from . forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact' ),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('generate/', views.generate, name= 'generate'),
    path('generate/generateQuestions', views.generateQuestions, name='generateQuestions'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',authentication_form = LoginForm), name='login'),
]

quizko/Quizko/Quizko/urls.py
from django.contrib import admin
from django.urls import path, include

from Core.views import browse


urlpatterns = [
    path('', include('Core.urls')),
    path('browse/quiz/', include('item2.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path("admin/", admin.site.urls),
    path('browse/', browse, name='browse'),
]

quizko/Quizko/conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

quizko/Quizko/dashboard/urls.py
from django.urls import path

from . import views 

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('editForm', views.editForm, name='editForm'),  
    path('deleteForm', views.deleteForm, name="deleteForm"),
    path('getLoadData', views.getLoadData, name='getLoadData'),
]

quizko/Quizko/Core/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

quizko/Quizko/item2/models.py
from django.db import models
from django.contrib.auth.models import User
import random
from django.utils import timezone


class Quiz(models.Model):
    STATUS_CHOICES = [
        ('ready', 'Ready to use'),
        ('testing', 'Needs testing'),
        ('draft', 'Draft'),
    ]
    
    title = models.CharField(max_length=255)
    description = models.TextField()
    difficulty = models.CharField(max_length=20)
    time = models.IntegerField(default=0, help_text = "Duration of the quiz in minutes.")
    number_of_questions = models.IntegerField(default=1)
    required_score_to_pass = models.IntegerField(help_text = "required score to pass", default = 0)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='draft')
    subject = models.CharField(max_length=100, default='')  # New field for subject
    
    class Meta:
        verbose_name_plural = 'Quizzes'

    
    def get_questions(self):
        return self.question_set.all()[:self.number_of_questions]
    
    def __str__(self):
        return self.title
    
class Result(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self) -> str:
        return str(self.score)

class Question(models.Model):
    text = models.TextField()
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def get_answers(self):
        return self.answer_set.all()

    def __str__(self):
        return self.text

# Create your models here.
class Answer(models.Model):
    text = models.CharField(max_length=255)
    is_correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return f'question: {self.question.text}, answer: {self.text}, correct: {self.is_correct}'
    

quizko/Quizko/Core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your Username',
        'class': 'w-full py-1 px-2 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Your password',
        'class': 'w-full py-1 px-2 rounded-xl'
    }))





class SignupForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your Username',
        'class': 'w-full py-1 px-2 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder':'Your email address',
        'class': 'w-full py-1 px-2 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Your password',
        'class': 'w-full py-1 px-2 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Repeat password',
        'class': 'w-full py-1 px-2 rounded-xl'
    }))

quizko/Quizko/Core/views.py
from django.shortcuts import render, redirect
from item2.models import Answer,Question,Quiz,Result
from item2.forms import QuizCreationForm, QuestionCreationForm
from django.views.generic import ListView
from .forms import SignupForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse
import pdb
from  django.db.models import Q

# Create your views here.
def index(request):
    return render(request, 'core/index.html')

def contact(request):
    return render(request, 'core/contact.html')


def aboutus(request):
    return render(request, 'core/aboutus.html')


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = SignupForm()
        
    return render(request, 'core/signup.html', {
        'form':form
    })

@login_required
def generate(request):
    form = QuizCreationForm()
    return render(request, 'core/generate.html', {'quiz_form': form})

@login_required
def generateQuestions(request):
    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        data = request.POST
        data_ = dict(data.lists())
        data_.pop('csrfmiddlewaretoken')
        # Iterate through the items and remove the prefix
        cleaned_data = {}
        for key, value in data_.items():
            cleaned_key = key.split('[')[-1][:-1]  # Extract what's inside the brackets
            cleaned_data[cleaned_key] = value

        # Now iterate over the cleaned data
        #for k, value in cleaned_data.items():
            #print('key: ', k)
            #print('OBJECT: ', value)

        cleaned_list = list(cleaned_data.items())

        quiz_list = []
        quiz_list.extend(cleaned_list[1:6])
        quiz_list.extend(cleaned_list[-2:])
        del cleaned_list[1:6]
        del cleaned_list[-2:]
        quizCreated = Quiz(title = quiz_list[0][1][0], description=quiz_list[1][1][0],
         difficulty=quiz_list[2][1][0], time=int(quiz_list[3][1][0]), number_of_questions=int(quiz_list[4][1][0]),
         creator=request.user, required_score_to_pass=int(quiz_list[5][1][0]), subject=quiz_list[6][1][0])
        quizCreated.save()
        del cleaned_list[0]
        while len(cleaned_list) > 0:
            questionCreation = Question(text = cleaned_list[0][1][0], quiz=quizCreated)
            questionCreation.save()
            answer1 = Answer(text = cleaned_list[1][1][0], is_correct = True, question= questionCreation)
            answer1.save()
            answer2 = Answer(text = cleaned_list[2][1][0], is_correct = False, question= questionCreation)
            answer2.save()
            answer3 = Answer(text = cleaned_list[3][1][0], is_correct = False, question= questionCreation)
            answer3.save()
            answer4 = Answer(text = cleaned_list[4][1][0], is_correct = False, question= questionCreation)
            answer4.save()
            del cleaned_list[0:5]

        return JsonResponse({'text':'works'})
    return JsonResponse({'text':'not Working'})


#class QuizListView(ListView):
#    model = Quiz
#    template_name ='core/browse.html'

def browse(request):
 query = request.GET.get('query', '')
 quizzes = Quiz.objects.all()
 
 if query:
     quizzes = quizzes.filter(Q(title__icontains=query) | Q(description__icontains=query))

 return render(request, 'core/browse.html', {
  'quizzes': quizzes
 })

quizko/Quizko/Core/templates/core/aboutus.html
{% extends 'core/base.html'%}
{% load static %}
{% block title%}About us {%endblock%}

{% block content %}
<link rel="stylesheet" href ="{% static 'homestyles1.css'%}">
<link rel="stylesheet" href ="{% static 'aboutus.css'%}">
<main>
    <article class="flow">
      <h1 class="aboutusTitle">About Us</h1>
      <p class="lead">" Our platform empowers users to create and share quizzes on a wide range of topics, from history and science to pop culture and beyond. Whether you're a teacher looking to gamify your lessons, a student wanting to test your knowledge, or just someone who loves trivia, QuizMaster is your go-to destination."</p>
      <div class="aboutusHero">
      <div class="aboutusHeroSection left"><h2>Our company values</h2>
      </div>
      <div class="aboutusHeroSection right">
        <div class="value commitment">
          <h3>Commitment</h3>
          <p class="aboutusValues">Openness with our team & clients. We raise issues & provide solutions promptly.</p>
        </div>
        <div class="value transparency">
          <h3>Transparency</h3>
          <p class="aboutusValues">Our word and hard work over everything else. Our clients and vision are our guiding beacons</p>
        </div>
        <div class="value selfImprovement">
          <h3>Self Improvement</h3>
          <p class="aboutusValues">Never stop learning, never stop evolving into who we want to be and where we want to be.</p>
        </div>
        <div class="value overDeliver">
          <h3>Over Deliver</h3>
          <p class="aboutusValues">Deliver more value than our team & clients expect. Every day, over every delivery.</p>
        </div>

      </div>
      
      </div>
    
    </article>
    <article class="two-column">
      <p class="aboutusLead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestiae modi ab recusandae aliquid perspiciatis
        unde dolorum id natus velit vel, facere excepturi similique nemo enim quasi nam, expedita inventore? Repellat
        aspernatur ducimus facilis nemo omnis sunt unde, vel doloribus error enim id deleniti saepe placeat.
      </p>
      <p class="aboutusColumnText">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestiae modi ab recusandae aliquid perspiciatis
          unde dolorum id natus velit vel, facere excepturi similique nemo enim quasi nam, expedita inventore? Repellat
          aspernatur ducimus facilis nemo omnis sunt unde, vel doloribus error enim id deleniti saepe placeat.
      </p>
      <p class="aboutusColumnText">Voluptatem <a href="#">ipsum tempora vel quisquam</a> cumque natus nesciunt vitae ipsam in inventore, earum eligendi impedit.
          <a href="https://google.com">Sunt quis veniam</a> numquam vitae, magnam, debitis reiciendis in voluptas porro voluptatum, est consequuntur
          illo! Assumenda saepe aliquid eos fugiat rerum similique sequi illo velit amet officia voluptas, sed ducimus.
        </p>
      <p class="aboutusColumnText">Quasi necessitatibus mollitia quisquam officiis molestiae fugiat officia cumque tempora accusamus adipisci
          quia, suscipit earum rerum illo, fugit architecto fuga eius error labore! Ducimus voluptate quae aliquid
          obcaecati beatae exercitationem quaerat molestiae quos, atque dolorum id quo sint vero sit reiciendis cumque
          consectetur molestias temporibus.</p>
      <blockquote>"Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis, blanditiis."</blockquote>
      <p class="aboutusColumnText">Molestiae magnam similique dolorum vero libero doloribus neque, voluptas natus sunt facere ipsa cupiditate
        placeat necessitatibus cum perferendis ducimus deserunt architecto nesciunt, illum ab aliquid minus
        dignissimos dolore voluptatibus? Perferendis, incidunt! Repellendus numquam nobis quidem totam dolor aliquid.
        Placeat rerum eveniet doloribus asperiores quis iusto!</p>
  </article>
  </main>

{% endblock %}

quizko/Quizko/Core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
    
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock%} | Quizko</title>
        {% load static %}
        <link rel="stylesheet" href ="{% static 'base1.css'%}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>      
</head>
<body>
    <nav>
        <a href="/" class="logo">Quizko</a>
        <ul>
            <li><a href="{%url 'core:generate' %}">Generate</a></li>
            <li><a href="{%url 'browse' %}">Browse</a></li>

            {% if request.user.is_authenticated %}
            <li class="button1"><a href="{%url 'conversation:inbox' %}">Inbox</a></li>
            <li class="button2"><a href="{%url 'dashboard:index' %}">Dashboard</a></li>

            {% else %}
            <li class="button1"><a href="{%url 'core:signup' %}">Sign Up</a></li>
            <li class="button2"><a href="{%url 'core:login' %}">Log in</a></li>
            {%endif%}
        </ul>
    
    </nav>
    <div id="contentBody">

        
        {% block content %}
        {% endblock %}

    </div>

    <footer>
         <div class="containerDiv">
                <h4>About</h4>
                <br>
                 <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p>             
        </div>
        <div class="footerMenu">
            <h4>Menu</h4>
            <ul class="footerList">
               <p><a href="{%url 'core:aboutus' %}" class="footerA">About Us</a></p>
               <p><a href="{%url 'core:contact' %}" class="footerA">Contact</a></p>
               <p><a href="" class="footerA">Privacy Policy</a></p>
               <p><a href="" class="footerA">Terms of use</a></p>
            </ul>

        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

quizko/Quizko/Core/templates/core/browse.html
{% extends 'core/base.html'%}
{% load static %}
{% block title%}Contact {%endblock%}
{% block scripts %}
 
{% endblock scripts %}

{% block content %}
<script src="{% static 'browse.js' %}" defer></script>
<link rel="stylesheet" href ="{% static 'homestyles.css'%}">
<link rel="stylesheet" href ="{% static 'browse.css'%}">
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="exampleModalLabel" style="color: black;">Start Test?</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="modal-body-confirm">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">No</button>
        <button type="button" id="start-button" class="btn btn-success">Yes</button>
      </div>
    </div>
  </div>
</div>
<div class="pb-6 grid grid-cols-4 gap-4">
<div class="col-span-1" id="searchable">
  <h5>Search quizzes</h5>
 <form method="get" action="{%url 'browse' %}">
 <div class="input-group mb-3">
  <input name="query" class="form-control" type="text" value="{{ query }}" placeholder="Find a quiz...">
  <button class="btn btn-outline-secondary">Search</button> 
 </div>
</form>
</div>
<h5 class="font-semibold">Clear filters</h5>
<li><a class="btn btn-warning" href="{% url 'browse' %}" role="button">Clear</a></li>
<div class="col-span-3">
  <div class="card">
    <div class="card-body" style="align-items: center; justify-content: center;">
      <H2 style="align-items: center; text-align: center; color: aliceblue;">Browse quizzes</H2>
      {% for item in quizzes %}
      <div class="list-group" style="padding-right: 20%; padding-left: 20%;">
      <a href="#" class="list-group-item list-group-item-action modal_clickable" data-bs-toggle="modal" data-bs-target="#exampleModal"
      data-pk="{{item.pk}}"
            data-quiz ="{{item.title}}"
            data-questions="{{item.number_of_questions}}"
            data-difficult="{{item.difficulty}}"
            data-time="{{item.time}}"
            data-pass="{{item.required_score_to_pass}}"
            data-bs-toggle="modal"
            data-bs-target="#quizStartModal">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">{{ item.title }}</h5>
          <small class="text-body-secondary" style="color:black ;">{{ item.get_status_display }}</small>
        </div>
        <p class="mb-1" style="color:black ;">{{ item.description }}.</p>
        <small class="text-body-secondary" style="color:black ;">Author: {{ item.creator }}</small>
      </a>
      </div>
      <br>
      {% endfor %}
    </div>
  </div>
</div>
</div>


{% endblock %}

quizko/Quizko/Core/templates/core/contact.html
{% extends 'core/base.html'%}
{% load static %}
{% block title%}Contact us{%endblock%}

{% block content %}
<link rel="stylesheet" href ="{% static 'homestyles.css'%}">
<div class="contactSection">
    <h2 class="contactTitle">The Contact us Page</h2>
</div>

{% endblock %}

quizko/Quizko/Core/templates/core/generate.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'homestyles.css' %}">
<link rel="stylesheet" href="{% static 'generate.css' %}">

<div class="form-container">
    <p class="d-flex gap-1">
        <button id="expandButton" class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExampleQuiz" aria-expanded="false" aria-controls="collapseExample">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrows-expand" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 0 1h-13A.5.5 0 0 1 1 8M7.646.146a.5.5 0 0 1 .708 0l2 2a.5.5 0 0 1-.708.708L8.5 1.707V5.5a.5.5 0 0 1-1 0V1.707L6.354 2.854a.5.5 0 1 1-.708-.708zM8 10a.5.5 0 0 1 .5.5v3.793l1.146-1.147a.5.5 0 0 1 .708.708l-2 2a.5.5 0 0 1-.708 0l-2-2a.5.5 0 0 1 .708-.708L7.5 14.293V10.5A.5.5 0 0 1 8 10"/>
            </svg>
        </button>
    </p>
    <div class="collapse" id="collapseExampleQuiz" style="width: 80%;">
        <div class="card card-body" id="card-body">
            <form onsubmit="return false" id="quiz-form" action="." method="post" enctype="multipart/form-data" class="form-content" style="display:flex; flex-direction: column;">
                {% csrf_token %}
                <h1 style="text-align: center;color: black;"> Design Your Quiz</h1>
                <div class="mb-3">
                    <label for="title" class="form-label" style="color: black;"><b>Title</b></label>
                    {{ quiz_form.title }}
                </div>
                <div class="mb-3">
                    <label for="description" class="form-label"><b>Description</b></label>
                    {{ quiz_form.description }}
                </div>
                <div class="mb-3">
                    <label for="difficulty" class="form-label"><b>Difficulty</b></label>
                    {{ quiz_form.difficulty }}
                </div>
                <div class="mb-3">
                    <label for="time" class="form-label"><b>Time (minutes)</b></label>
                    {{ quiz_form.time }}
                </div>
                <div class="mb-3">
                    <label for="number_of_questions" class="form-label"><b>Number of Questions</b></label>
                    <span id="number_of_questions_text" style="display: none;">{{ quiz_form.number_of_questions }}</span>
                    <div style="display: flex;gap: 5px;">
                     {{ quiz_form.number_of_questions }}
                     <button style="padding-top: 4px;" onclick="questionButtonAction()" id="expandButtonQuestion" class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExampleQuestion" aria-expanded="false" aria-controls="collapseExample">
                            +
                     </button>
                    </div>
                    
                    <label for=""><b>Please generate questions. Select each page and complete accordingly.</b></label>
                    <br>
                    
                    <div id="questionDiv" style="width: 100%;">

                   </div>
                </div>
                <div class="mb-3">
                    <label for="required_score_to_pass" class="form-label"><b>Required Score to Pass</b></label>
                    {{ quiz_form.required_score_to_pass }}
                </div>
                <div class="mb-3">
                    <label for="subject" class="form-label"><b>Subject</b></label>
                    {{ quiz_form.subject }}
                </div>
                {% if quiz_form.errors or quiz_form.non_field_errors %}
                <div style="margin-bottom: 3px; padding: 6px; background-color: red; border-radius: 6px;">
                    {% for field in quiz_form %}
                    {{ field.errors }}
                    {% endfor %}

                    {{ quiz_form.non_field_errors }}
                </div>
                {% endif %}
                <br>
                <br>
                <button onclick="submitQuiz()" type="submit" class="btn btn-info" id="submitButton">Submit</button>
            </form>
          </div>
        </div>
    </div>
</div>
<script src="{% static 'generate.js' %}" defer></script>
{% endblock %}

quizko/Quizko/Core/templates/core/index.html
{% extends 'core/base.html'%}
{% load static %}
{% block title%}Welcome{%endblock%}

{% block content %}
<link rel="stylesheet" href ="{% static 'homestyles.css'%}">
    
    <main>
        <div class = "container"> 
         <img src="{% static 'screen.png' %}" alt="">
         <div class="hero-text">
            <h1>Discover And Create Your Own Quizzes!</h1>
            <p>Quizko is a web-based assessment and learning website. It comprises tools to create general quizzes to improve knowledge.</p>
            <button><a href="{%url 'core:login' %}">Log in</a></button> 
            <BUtton class="signup"><a href="{%url 'core:signup' %}">Sign up</a></BUtton>
        </div>
        </div>
        <br>
        <br>
        <div class="featured">
            <p class="featured-text">
                FEATURED ON:
            </p>
            <div class="featured-tab">
                <img src="{% static 'brand1.png' %}" alt="" class="brand1">
                <img src="{% static 'brand2.png' %}" alt="" class="brand2">
                <img src="{% static 'brand3.png' %}" alt="" class="brand3">
                <img src="{% static 'brand4.png' %}" alt="" class="brand4">

            </div>
        </div>
        <br>
        <br>
        <div class="container2">
            <img src="{% static 'secondHero.png' %}" alt="" class="secondHero">
            <div class="hero2-text">
                <h1>Built in analytics to track your tests.</h1>
                <p>Use our built-in dashboard to pull valuable insights from tests and monitor the value of your Quizko account.</p>
                <button><a href="{%url 'core:generate' %}">Generate test</a></button>
            </div>
        </div>
        <div class = "container"> 
            <img src="{% static 'hero3.png' %}" alt="">
            <div class="hero-text">
               <h1>Our Quizko app is the easiest way to make tests on the go.</h1>
               <p>Browse tests from your smartphone!</p>
               <button>Get the App</button> 
           </div>
           </div>
        <br>
        <br>
        <section class="testimonials">
            <div class = "title">
                <h2>Testimonials</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, magni quas tempore quod, voluptatibus officia facere rem cum ab et, possimus obcaecati saepe at unde eius eligendi error sint doloribus?</p>
            </div>
            <div class="row">
                <div class="col">
                <img src="{% static 'test1.png' %}" alt="">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet, aut placeat exercitationem enim aspernatur ullam, earum, sunt veritatis tempore inventore expedita vero corrupti. Beatae, natus magnam. Voluptatem eveniet laborum esse!</p>
                <h4>Kelly John   </h4>
                </div>
                <div class="col">
                 <img src="{% static 'test2.png' %}" alt="">
                 <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet, aut placeat exercitationem enim aspernatur ullam, earum, sunt veritatis tempore inventore expedita vero corrupti. Beatae, natus magnam. Voluptatem eveniet laborum esse!</p>
                 
                 <h4>John Snow</h4>
                </div>
                <div class="col">
                 <img src="{% static 'test3.png' %}" alt="">
                 <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet, aut placeat exercitationem enim aspernatur ullam, earum, sunt veritatis tempore inventore expedita vero corrupti. Beatae, natus magnam. Voluptatem eveniet laborum esse!</p>
                 <h4>Hali Snow   </h4>
                </div>
            </div>

        </section>
    </main>
{% endblock %}

quizko/Quizko/Core/templates/core/login.html
{% extends 'core/base.html'%}
{% load static %}
{% block title%}Log in{%endblock%}

{% block content %}
<link rel="stylesheet" href ="{% static 'homestyles.css'%}">
<link rel="stylesheet" href ="{% static 'login.css'%}">

<br><br>
<div class="signUpCentral" style="padding-bottom: 200px; padding-top: 60px;">
    <div class="mainContainer">
        <h1>Log in</h1>


        <form action="." method="post" style="padding-bottom: 1px;">
            {% csrf_token%}

            <div class="signUpBoxes">
                <label for="" style="margin-bottom: 3px;">Username</label>
                {{form.username}}
            </div>

            <div class="signUpBoxes">
                <label for="" style="margin-bottom: 3px;">Password</label>
                {{form.password}}
            </div>

            {% if form.errors or form.non_field_errors%}
              <div style="margin-bottom: 3px; padding: 6px; background-color: red; border-radius: 6px;">
              {% for field in form %}
                {{field.errors}}
              {% endfor%}

              {{form.non_field_errors}}
             </div>
            {% endif %}

            <button type="submit" class="btn btn-info">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

quizko/Quizko/Core/templates/core/signup.html
{% extends 'core/base.html'%}
{% load static %}
{% block title%}Sign Up{%endblock%}

{% block content %}
<link rel="stylesheet" href ="{% static 'homestyles.css'%}">
<link rel="stylesheet" href ="{% static 'signup.css'%}">

<br><br>
<div class="signUpCentral" style="padding-bottom: 30px;">
    <div class="mainContainer">
        <h1>Sign Up</h1>


        <form action="." method="post" style="padding-bottom: 1px;">
            {% csrf_token%}

            <div class="signUpBoxes">
                <label for="" style="margin-bottom: 3px;">Username</label>
                {{form.username}}
            </div>

            <div class="signUpBoxes">
                <label for="" style="margin-bottom: 3px;">Email</label>
                {{form.email}}
            </div>

            <div class="signUpBoxes">
                <label for="" style="margin-bottom: 3px;">Password</label>
                {{form.password1}}
            </div>

            <div class="signUpBoxes">
                <label for="" style="margin-bottom: 3px;">Repeat Password</label>
                {{form.password2}}
            </div>

            {% if form.errors or form.non_field_errors%}
              <div style="margin-bottom: 3px; padding: 6px; background-color: red; border-radius: 6px;">
              {% for field in form %}
                {{field.errors}}
              {% endfor%}

              {{form.non_field_errors}}
             </div>
            {% endif %}

            <button type="submit" class="btn btn-info">Submit</button>
        </form>
    </div>
</div>
{% endblock %}