quizko/Quizko/Core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from . forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact' ),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('generate/', views.generate, name= 'generate'),
    path('generate/generateQuestions', views.generateQuestions, name='generateQuestions'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',authentication_form = LoginForm), name='login'),
]

quizko/Quizko/Quizko/urls.py
from django.contrib import admin
from django.urls import path, include

from Core.views import browse


urlpatterns = [
    path('', include('Core.urls')),
    path('browse/quiz/', include('item2.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path("admin/", admin.site.urls),
    path('browse/', browse, name='browse'),
]

quizko/Quizko/conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

quizko/Quizko/item2/urls.py
from django.urls import path

from .views import(
    detail,
    quiz_data_view,
    save_quiz_view,
)

app_name = 'quiz'

urlpatterns = [
    path('<int:pk>/', detail, name='detail'),
    path('<int:pk>/save/', save_quiz_view, name='save-view'),
    path('<int:pk>/data/', quiz_data_view, name='quiz-data-view'),
]

quizko/Quizko/item2/models.py
from django.db import models
from django.contrib.auth.models import User
import random
from django.utils import timezone


class Quiz(models.Model):
    STATUS_CHOICES = [
        ('ready', 'Ready to use'),
        ('testing', 'Needs testing'),
        ('draft', 'Draft'),
    ]
    
    title = models.CharField(max_length=255)
    description = models.TextField()
    difficulty = models.CharField(max_length=20)
    time = models.IntegerField(default=0, help_text = "Duration of the quiz in minutes.")
    number_of_questions = models.IntegerField(default=1)
    required_score_to_pass = models.IntegerField(help_text = "required score to pass", default = 0)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='draft')
    subject = models.CharField(max_length=100, default='')  # New field for subject
    
    class Meta:
        verbose_name_plural = 'Quizzes'

    
    def get_questions(self):
        return self.question_set.all()[:self.number_of_questions]
    
    def __str__(self):
        return self.title
    
class Result(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self) -> str:
        return str(self.score)

class Question(models.Model):
    text = models.TextField()
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def get_answers(self):
        return self.answer_set.all()

    def __str__(self):
        return self.text

# Create your models here.
class Answer(models.Model):
    text = models.CharField(max_length=255)
    is_correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return f'question: {self.question.text}, answer: {self.text}, correct: {self.is_correct}'
    

quizko/Quizko/item2/forms.py
from django import forms
from .models import Quiz,Question,Answer
from django.contrib.auth.models import User

from django import forms
from .models import Quiz

from django import forms
from .models import Question

class QuestionCreationForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['text', 'quiz']
        labels = {
            'text': 'Question Text',
            'quiz': 'Associated Quiz'
        }
        widgets = {
            'text': forms.Textarea(attrs={'rows': 4, 'placeholder': 'Enter your question here', 'class': 'form-control'}),
            'quiz': forms.Select(attrs={'class': 'form-select'})
        }



class QuizCreationForm(forms.ModelForm):
    DIFFICULTY_CHOICES = [
        ('easy', 'Easy'),
        ('medium', 'Medium'),
        ('hard', 'Hard'),
    ]

    difficulty = forms.ChoiceField(choices=DIFFICULTY_CHOICES, widget=forms.Select(attrs={
        'class': 'form-select',
        'placeholder': 'Select difficulty'
    }))

    class Meta:
        model = Quiz
        fields = ['title', 'description', 'difficulty', 'time', 'number_of_questions', 'required_score_to_pass', 'subject']
        labels = {
            'title': 'Title',
            'description': 'Description',
            'time': 'Time (in minutes)',
            'number_of_questions': 'Number of Questions',
            'required_score_to_pass': 'Required Score to Pass',
            'subject': 'Subject'
        }
        widgets = {
            'title': forms.TextInput(attrs={
                'placeholder': 'Title of your quiz',
                'class': 'form-control'
            }),
            'description': forms.Textarea(attrs={
                'rows': 4,
                'placeholder': 'Your test is about...',
                'class': 'form-control'
            }),
            'time': forms.NumberInput(attrs={
                'min': 1,
                'placeholder': 'Timed duration of your test',
                'class': 'form-control'
            }),
            'number_of_questions': forms.NumberInput(attrs={
                'min': 1,
                'placeholder': 'Total questions',
                'class': 'form-control'
            }),
            'required_score_to_pass': forms.NumberInput(attrs={
                'min': 1,
                'placeholder': 'Enter required score to pass',
                'class': 'form-control'
            }),
            'subject': forms.TextInput(attrs={
                'placeholder': 'Subject of your quiz',
                'class': 'form-control'
            })
        }

quizko/Quizko/item2/views.py
from django.shortcuts import render, get_object_or_404
import json
from .models import Quiz,Answer,Question,Result
from django.views.generic import ListView
from django.http import JsonResponse
import random
import math



def detail(request, pk):
    quiz = get_object_or_404(Quiz, pk=pk)
    
    return render(request, 'quiz/detail.html', {
        'obj': quiz,
    })

def quiz_data_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    for q in quiz.get_questions():
        answers=[]
        for a in q.get_answers():
            answers.append(a.text)
        random.shuffle(answers)
        questions.append({str(q):answers})
    random.shuffle(questions)
    return JsonResponse({
     'data':questions,
     'scorePass': quiz.required_score_to_pass,
     'time': quiz.time
    })
        
def save_quiz_view(request, pk):
    print(request.POST)
    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        questions = []
        data = request.POST
        data_ = dict(data.lists())
        data_.pop('csrfmiddlewaretoken')
        for k in data_.keys():
            print('key: ', k)
            question = Question.objects.get(text=k)
            questions.append(question)
        print(questions)
        user = request.user
        quiz = Quiz.objects.get(pk=pk)

        score = 0
        multiplier = 100 / quiz.number_of_questions
        results = []
        correct_answer = None
        for q in questions:
            a_selected = request.POST.get(q.text)
            if a_selected !="":
                question_answers = Answer.objects.filter(question=q)
                for a in question_answers:
                    if a_selected == a.text:
                        if a.is_correct:
                            score+=1
                            correct_answer=a.text
                    else:
                            if a.is_correct:
                                correct_answer = a.text
                results.append({str(q): {'correct_answer': correct_answer , 'answered': a_selected}})
            else:
                results.append({str(q): 'not answered'})

        score_ = score * multiplier
        result = Result.objects.create(quiz=quiz, user=user, score=score_)
        result.save()

        if score_ >= quiz.required_score_to_pass:
            return JsonResponse({'passed':True, 'score':round(score_,2), 'results': results})
        else:
            return JsonResponse({'passed':False, 'score':round(score_,2), 'results': results})


    return JsonResponse({'text':'works'})

quizko/Quizko/item2/templates/quiz/detail.html
{% extends 'core/base.html'%}
{% load static %}
{% block title%} {{obj.title}} {% endblock %}
{}

{% block content %}

<link rel="stylesheet" href="{% static 'homestyles.css' %}">
<link rel="stylesheet" href="{% static 'detail.css' %}">
<script src="{% static 'detail.js' %}" defer></script>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header">
            <h1 class="modal-title" id="exampleModalLabel" style="color: black;">Results</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          Results:
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary"><a href="{%url 'browse' %}" style="color: white;">Complete</a></button>
        </div>
      </div>
    </div>
  </div>
<div class="detailTitle">
    <p class="detailTitleText">{{ obj.title }}</p>
    <p>in</p>
    <p class="detailTitleText">{{ obj.subject }}</p>
    <div id="timer-box"></div>

</div>
<div class="detailScroll">
    <nav class="sidebar">
        <header>
            <h2 class="detailHeader">Quizko</h2>
            <h3 class="detailHeader">{{ obj.title }}</h3>
        </header>
        <div class="scrollbox">
            <div class="scrollbox-inner" id="scrollbox-inner">
                {% for question in questions %}
                <div>
                    <h2></h2>
                </div>
                {% endfor %}
                <br>
            </div>
        </div>
        <div class="detailFooter">
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-warning"><a href="{%url 'browse' %}" style="color: white;">Return</a></button>
            <br>
            <button type="button" class="btn btn-danger btn-lg" data-bs-toggle="modal" data-bs-target="#exampleModal" id="submitQuiz" style="visibility: hidden;">
             End Exam
            </button>
            <a class="btn btn-primary" href="{% url 'conversation:new' obj.id %}" role="button">Add comments</a>   
        </div>
    </nav>
    <div class="detailContent">
        <h2 class="detailContentTextDefault">Contents</h2>
        <form id="quiz-form">
            {% csrf_token %}
            <div id="quiz-box"></div>
            
        </form>
    </div>
</div>

<script>

</script>
{% endblock %}